In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem

smiles1 = "O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O"
smiles2 = "O=C(C1=CC(C(O)=O)=C(C(O)=O)C=C1C(O)=O)O"
smiles3 = "FC1=C(F)C(F)=C(C(O)=O)C(C(O)=O)=C1F"

def get_idx(smiles):
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)  # 水素を追加
    phthalic_pattern = Chem.MolFromSmarts("c1ccc(C(=O)O)c(C(=O)O)c1")
    
    # フタル酸構造を持つかどうか
    matches_data = mol.GetSubstructMatches(phthalic_pattern)
    print(matches_data)
    atoms = ""
    for match in matches_data[0]:
        atom = mol.GetAtomWithIdx(match)  # その番号の原子の情報
        symbol = atom.GetSymbol()
        neighbors = atom.GetNeighbors()
        for neighbor in neighbors:
            idx = neighbor.GetIdx()
            # print(idx)
        atoms += f"{match}: {symbol}, "
    print(atoms)
    print(type(matches_data[0][0]))

get_idx(smiles1)
get_idx(smiles2)
get_idx(smiles3)

In [1]:
import rdkit_calc as rc
import phthalicacid as pa
import pandas as pd

df = pd.read_csv("out/save/samples.csv")
df = rc.sub_idx(df)
print(df[["3and6", "4and5"]])

    3and6  4and5
0       0      0
1       0      2
2       0      2
3       0      1
4       1      0
5       0      1
6       0      1
7       0      1
8       0      2
9       0      1
10      1      0
11      0      1
12      0      1
13      0      1
14      1      0
15      0      1
16      0      1
17      0      2
18      0      1
19      0      2
20      0      2
21      1      0
22      2      2


In [ ]:
import pandas as pd
import rdkit_calc as rc

df = pd.read_csv("out/save/value.csv")
df = rc.sub_idx(df)
print(df.head())

         cas                                   smiles  h1  h2  \
0    88-99-3                  O=C(C1=CC=CC=C1C(O)=O)O  17  16   
1  2169-87-1          O=C(C1=CC2=CC=CC=C2C=C1C(O)=O)O  23  22   
2    89-05-4  O=C(C1=CC(C(O)=O)=C(C(O)=O)C=C1C(O)=O)O  19  20   
3   610-27-5         O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O  15  19   
4   603-11-2         O=C(O)C1=CC=CC(=C1C(=O)O)N(=O)=O  15  19   

   delta_g_hartree  dipole_moment_debye   homo_ev   lumo_ev    gap_ev  \
0         0.438380             1.282205 -8.984111 -0.688720  8.295391   
1         0.438607             2.529908 -7.840416 -0.689536  7.150880   
2         0.434274             4.369587 -9.310375 -1.383427  7.926949   
3         0.433323             6.392675 -9.433915 -1.997860  7.436055   
4         0.434331             5.063714 -9.406432 -1.915954  7.490478   

   molecular_volume_A3  nbo_charge  yield 3rd 4th 5th 6th  
0              139.352     0.53188  13.32   0   0   0   0  
1              182.672     0.53189  11.80   0   1 

In [2]:
df.to_csv("out/save/value.csv", index=False)

In [2]:
import pandas as pd

df = pd.read_csv("out/save/samples.csv")
df.drop(1,inplace=True)
print(df.head())
print(df.columns)

        cas                                             smiles  h1  h2
0   88-99-3                            O=C(C1=CC=CC=C1C(O)=O)O  17  16
2   89-05-4            O=C(C1=CC(C(O)=O)=C(C(O)=O)C=C1C(O)=O)O  19  20
3  610-27-5                   O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O  15  19
4  603-11-2                   O=C(O)C1=CC=CC(=C1C(=O)O)N(=O)=O  15  19
5        te  O=C(C(C=C1)=C(C(O)=O)C=C1OC2=CC(OC3=CC=C(C(O)=...  62  47
Index(['cas', 'smiles', 'h1', 'h2'], dtype='object')


In [25]:
a = ["gap","delta_g","homo","lumo","dipole_moment"]
b = "|".join(a)
print(b)

gap|delta_g|homo|lumo|dipole_moment


In [3]:
import pandas as pd

a = pd.read_csv("out/predict/gauss_train.csv")
print(a["r2"].max())

0.497301126793259


In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("out/predict/samples_1-100_ver1.csv")

max_sigma = np.argmax(df["sigma"])
max_ei = np.argmax(df["ei"])

print(df.loc[max_sigma, "cas"])
print(df.loc[max_ei, "cas"])

90348-28-0
90348-28-0


In [6]:
sigma_idx = np.argsort(df["sigma"])[::-1]
for idx in sigma_idx:
    print(df.loc[idx, "cas"],"  ", df.loc[idx, "sigma"])

88-99-3    1.9683474854523175
603-11-2    3.260707566775962
610-35-5    2.2728621887239164
610-27-5    4.178771441142088
528-44-9    2.087848085707755
89-05-4    2.502885669933636
1885-13-8    2.52634292534398
569-51-7    2.181918938333722
6968-28-1    1.987198228272885
1583-67-1    2.082410298407932
137071-78-4    2.254691640625082
651-97-8    2.073677280920185
320-97-8    1.9605256298835232
5434-20-8    2.462141376648718
2169-87-1    2.172233342721517
22803-05-0    2.8288453039320283
116-69-8    2.109738174773904
3786-46-7    2.324504576793599
89-20-3    1.9858360434391067
4316-23-8    2.108056187774774
14963-97-4    2.785590686725919
10351-75-4    3.835828487889202
632-58-6    2.311479769707516
37141-01-8    5.042945644816781
835-58-5    2.501145384521559
37102-74-2    2.207568165501447
201730-11-2    2.1877491433934826
1585-40-6    3.752447226244509
601-97-8    2.591652022421595
27563-65-1    2.1102063630408563
3807-81-6    5.487901961006311
2479-49-4    2.940103936063976
24063-28-

In [ ]:
for idx in sigma_idx:
    print(df.loc[idx, "smiles"])

In [1]:
import pandas as pd
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
df = pd.DataFrame(a)
print(df)

   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12


In [2]:
import numpy as np
X = np.array(df)
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
import numpy as np
import pandas as pd

df = pd.read_csv("out/predict/unknown_1-200_ver1.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'out/predict/unknown_1-200_ver1.csv'

In [4]:
df = df.sort_values(by="sigma", ascending=False)
print(df.head())

             cas                                     smiles  h1  h2   homo_ev  \
72    90348-28-0  O=C(O)C=1C=C(C(=CC1C(=O)O)N(=O)=O)N(=O)=O  18  21 -9.789024   
150  213611-98-4          N#CC=1C=C(C(=O)O)C(=CC1C#N)C(=O)O  17  19 -9.493508   
57    92971-15-8  O=C(O)C1=CC=C(C(=C1C(=O)O)N(=O)=O)N(=O)=O  18  21 -9.758003   
86   209324-65-2  O=C(O)C1=CC=C(C(NC(=O)C)=C1C(=O)O)N(=O)=O  19  26 -8.756352   
77    22179-20-0        O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)N  16  20 -9.312280   

      lumo_ev    gap_ev  dipole_moment_debye  3and6  4and5        mu  \
72  -2.428344  7.360680             9.481184      0      2  3.283600   
150 -1.824251  7.669257             9.403363      0      2  2.543296   
57  -2.302355  7.455647             9.060131      1      1  2.737311   
86  -1.808741  6.947611             9.056428      1      1  2.045255   
77  -1.055530  8.256751             9.034061      0      1  1.833037   

        sigma        ei  
72   6.657869  0.029109  
150  6.449660  0.016220  
57